### ISSUE TITLE
provide ability to produce "native" ostree commit tar files

### ISSUE THREAD

**Issue by miabbott** [osbuild/images#133]
We got a customer report where they wanted to take an `edge-commit` artifact from osbuild and use it as an input to the `ostree commit` command, in order to generate a new commit using a new branch name:

`ostree --repo=/usr/share/nginx/html/repo commit --tree=tar=4b1d7096-3521-434a-bb35-a47672e11f2e-commit.tar --branch=new-branch`

ostree will happily accept this tarfile as an input, but the results are not what was expected by the customer.  This is because the tar file contains a `repo` directory and a `compose.json` file.  So when you inspect the new ostree commit, instead of a complete filesystem, you just get those two items:

```
[core@localhost ~]$ ostree --repo=/usr/share/nginx/html/newrepo refs
new-branch
[core@localhost ~]$ ostree --repo=/usr/share/nginx/html/newrepo rev-parse new-branch
9dc4d9117a16e168e807299b8cb50ddd11e8840a175cac647aa79feadc56a126
[core@localhost ~]$ ostree --repo=/usr/share/nginx/html/newrepo ls 9dc4d9117a16e168e807299b8cb50ddd11e8840a175cac647aa79feadc56a126
d00755 0 0      0 /
-00644 0 0    553 /compose.json
d00755 0 0      0 /repo
```

If a user tries to use that branch/commit as the input to `composer-cli compose start-ostree <blueprint> edge-raw-image`, the compose is going to fail because that commit doesn't have a complete filesystem.

What this customer likely expected was that the tar file was a "native" ostree commit tar file that is generated by `ostree export`, for example:

```
$ ostree --repo=/usr/share/nginx/html/minimal-repo export ebc39a2b34eaf019a692ca6af8cdb5b47cf43e82ff8aea620dc7a42a7fafffd2 > ostree-commit.tar
$ mkdir ostree-commit-tmp
$ tar -xf ostree-commit.tar -C ostree-commit-tmp/
$ ls -la ostree-commit-tmp/
total 8
drwxr-xr-x. 11 core weldr 4096 Aug 23 10:52 .
drwxr-xr-x.  6 core core  4096 Aug 23 14:40 ..
lrwxrwxrwx.  1 core weldr    7 Aug 23 10:52 bin -> usr/bin
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 boot
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 dev
lrwxrwxrwx.  1 core weldr    8 Aug 23 10:52 home -> var/home
lrwxrwxrwx.  1 core weldr    7 Aug 23 10:52 lib -> usr/lib
lrwxrwxrwx.  1 core weldr    9 Aug 23 10:52 lib64 -> usr/lib64
lrwxrwxrwx.  1 core weldr    9 Aug 23 10:52 media -> run/media
lrwxrwxrwx.  1 core weldr    7 Aug 23 10:52 mnt -> var/mnt
lrwxrwxrwx.  1 core weldr    7 Aug 23 10:52 opt -> var/opt
lrwxrwxrwx.  1 core weldr   14 Aug 23 10:52 ostree -> sysroot/ostree
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 proc
lrwxrwxrwx.  1 core weldr   12 Aug 23 10:52 root -> var/roothome
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 run
lrwxrwxrwx.  1 core weldr    8 Aug 23 10:52 sbin -> usr/sbin
lrwxrwxrwx.  1 core weldr    7 Aug 23 10:52 srv -> var/srv
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 sys
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 sysroot
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 tmp
drwxr-xr-x. 12 core weldr  155 Aug 23 10:52 usr
drwxr-xr-x.  2 core weldr    6 Aug 23 10:52 var
```

Then you can use the `ostree commit` command to generate a new commit on a new branch:

```
[core@localhost ~]$ sudo ostree --repo=/usr/share/nginx/html/repo commit --tree=tar=ostree-commit.tar --branch=imported-branch
ffae5e33a92d6cf8d4aabc81f25ae4b9095ff6f923e35beaf146706c2e816cec
[core@localhost ~]$ sudo ostree --repo=/usr/share/nginx/html/repo refs
imported-branch
new-branch
rhel/9/x86_64/edge
[core@localhost ~]$ sudo ostree --repo=/usr/share/nginx/html/repo rev-parse imported-branch
ffae5e33a92d6cf8d4aabc81f25ae4b9095ff6f923e35beaf146706c2e816cec
[core@localhost ~]$ sudo ostree --repo=/usr/share/nginx/html/repo ls ffae5e33a92d6cf8d4aabc81f25ae4b9095ff6f923e35beaf146706c2e816cec
d00755 0 0      0 /
l00777 0 0      0 /bin -> usr/bin
l00777 0 0      0 /home -> var/home
l00777 0 0      0 /lib -> usr/lib
l00777 0 0      0 /lib64 -> usr/lib64
l00777 0 0      0 /media -> run/media
l00777 0 0      0 /mnt -> var/mnt
l00777 0 0      0 /opt -> var/opt
l00777 0 0      0 /ostree -> sysroot/ostree
l00777 0 0      0 /root -> var/roothome
l00777 0 0      0 /sbin -> usr/sbin
l00777 0 0      0 /srv -> var/srv
d00755 0 0      0 /boot
d00755 0 0      0 /dev
d00755 0 0      0 /proc
d00755 0 0      0 /run
d00755 0 0      0 /sys
d00755 0 0      0 /sysroot
d01777 0 0      0 /tmp
d00755 0 0      0 /usr
d00755 0 0      0 /var
```

So....would it be reasonable to have osbuild be able to generate "native" ostree commit tar files for this kind of use case?

The use case of creating a new branch seems to be a common pattern for customers who want to change the branding (i.e. branch names) of RHEL for Edge before using it for their own purposes.

**Comment by miabbott** [comment]
I discovered that is possible to provide a `--ref` argument to `composer-cli compose start-ostree` and that can be used to generate an `edge-commit` using that ref name.  That could solve the use case I described, so this new functionality that I suggested may not be necessary.

**Comment by achilleas-k** [comment]
Yes, the `--ref` argument defines the ref for the new commit that's being built.  If that was the purpose of this request, can we close this issue?  Or do you think it would be good to be able to produce these kinds of files regardless?

**Comment by miabbott** [comment]
Let's close this for now; there may be additional use cases for this kind of artifact, but we haven't heard of strong demand for it yet.  If the situation changes, we can re-open it.
