### ISSUE TITLE
Use `bootc switch --mutate-in-place` for the Anaconda Container Installer

### ISSUE THREAD

**Issue by supakeen** [osbuild/images#380]
`bootc switch` is growing a new hidden option to change the origin in-place, we can use this in `%post` for the container installer to set the offline installer's origin to the right place: https://github.com/containers/bootc/pull/264

**Comment by cgwalters** [comment]
I looked into this and the main thing seems to be plumbing through all the layers of abstraction from:

- bib
- `NewAnacondaContainerInstaller()`
- `AnacondaInstallerISOTree::serialize()`
- `osbuild.NewKickstartStageOptionsWithOSTreeContainer`
- `osbuild.NewKickstartStage`

all the way to the `org.osbuild.kickstart` python code in osbuild - which does not seem to support `%post`.

So I *think* it'd be a matter of:

- adding `post` to that
- changing `osbuild.NewKickstartStageOptionsWithOSTreeContainer`
-

**Comment by cgwalters** [comment]
I guess though now I wonder whether it'd be worth trying to just add the kickstart option, given how prominent this is.

**Comment by cgwalters** [comment]
I did https://github.com/pykickstart/pykickstart/pull/471 just to try to start something here.

**Comment by supakeen** [comment]
Right now we have a shortcut in images to work with the relatively quickly changing landscape of this and write a kickstart file directly: https://github.com/osbuild/images/blob/main/pkg/manifest/anaconda_installer_iso_tree.go#L383

Though I much prefer having a kickstart option like you just linked because that's easier to move into the stage :)

**Comment by cgwalters** [comment]
Thanks yes, I just discovered that :smile: 

I'm attempting to hack this up right now.
