### ISSUE TITLE
Fedora 40 Workstation live is broken due to https://fedoraproject.org/wiki/Changes/AnacondaWebUIforFedoraWorkstation deferral

### ISSUE THREAD

**Issue by AdamWill** [osbuild/images#467]
https://fedoraproject.org/wiki/Changes/AnacondaWebUIforFedoraWorkstation got deferred to Fedora 41, so I reverted the gnome-initial-setup "live mode" patch and dropped anaconda-webui from the kickstart. However, the conditionals in osbuild (there are three separate webui-related conditional blocks, which seems like overkill, and they don't seem to agree on how to do the version check...) have not been updated for a while and all still want to apply webui to Fedora 40 images.

So, the current osbuild-built image is a bit broken because it still has anaconda-webui, but gnome-initial-setup doesn't have the live mode patch. This means you get the old-style "live desktop welcome screen" flow, but it launches the webui installer, which does not allow you to configure language and locale.

We need to either roll with making the osbuild image keep webui and be a way to try out webui on Fedora 40 - this would require building an alternate gnome-initial-setup package with the live mode patch, I guess, or making the patch somehow 'switchable' - or just go ahead and bump the version conditionals in osbuild so it doesn't put webui in F40 images. Not sure which approach we want to take.

**Comment by AdamWill** [comment]
@mcatanzaro thoughts?

**Comment by mcatanzaro** [comment]
Nope.

Reverting the gnome-initial-setup changes was correct.

**Comment by AdamWill** [comment]
okay, so if there's no interest in making it still-a-webui-image I guess we just need to bump the conditionals so we only put webui on rawhide.

**Comment by supakeen** [comment]
Note @AdamWill due to our chats on Matrix I have created two PRs to clean up those conditionals:

1. https://github.com/osbuild/images/issues/467
2. https://github.com/osbuild/images/pull/469

Otherwise, you can PR the conditional changes to bump it to 41.

**Comment by supakeen** [comment]
When the last PR (#479) lands this ticket will be complete right?

**Comment by AdamWill** [comment]
yep, indeed it should.

**Comment by supakeen** [comment]
Good, that one was merged :)
