### ISSUE TITLE
Is enabling of `AdditionalAnacondaModules` still necessary?

### ISSUE THREAD

**Issue by supakeen** [osbuild/images#474]
During review of #469 it came up that we enable `AdditionalAnacondaModules` conditionally on the Fedora version number here: https://github.com/osbuild/images/blob/main/pkg/distro/fedora/images.go#L359

I recall this had something to do with working on the webui and specifically the image-installer image type. Is this still necessary? It'd be nice if it can be gone entirely.

cc: @AdamWill @jkonecny12 @ondrejbudai.

**Comment by jkonecny12** [comment]
Hi, I guess these are here because they were not directly supported by web UI thus the modules were not started automatically. However, I'm not sure 100% @KKoukiou maybe you would know more?

My recommendation would be to leave it here for now. We can remove these later.

**Comment by supakeen** [comment]
I also looked through our internal Slack and @ondrejbudai found that I had enabled them because without the UI was acting up (reloading all the time because it couldn't query locales).

**Comment by KKoukiou** [comment]
Sorry I  had not reviewed this change, I am not aware of why it was introduced. We can try to remove these and see what happens.

**Comment by supakeen** [comment]
I'll do a build with them disabled, see what happens and then let you know.

**Comment by supakeen** [comment]
The result of the build is: they're no longer required and I've removed them in #484.
