### ISSUE TITLE
Fedora images have incorrect "BaseOS" in their ISO labels, fixing this is hard because of the templating design

### ISSUE THREAD

**Issue by AdamWill** [osbuild/images#487]
See https://bugzilla.redhat.com/show_bug.cgi?id=2264795#c12 . @ausil noticed that the ISO labels for Fedora images built by OSBuild - specifically the Workstation live image, but this actually applies to all of them - have "BaseOS" in them. So the label for a recent Workstation live built by OSBuild is `Fedora-40-BaseOS-x86_64`. That's obviously wrong. Nothing in Fedora is called BaseOS, that's a RHEL term.

By comparison, the ISO label for a livemedia-creator built Fedora Workstation live image is `Fedora-WS-Live-rawh-20240212-n-0` (fun fact: this format was vaguely formalized at https://fedoraproject.org/wiki/User:Adamwill/Draft_fedora_image_naming_policy forever ago, though it never stopped being a draft and isn't *quite* followed any more).

I wanted to fix this to make it at least `Fedora-40-Workstation-x86_64`, but this turns out to be surprisingly hard given how this is designed.

Basically the way it works is that each `distribution` struct is supposed to have an `isolabelTmpl` property which, as designed, should be a template string with *one* substitution marker, which is ultimately expected to be replaced by the architecture of the image (this is done in the various image types in `pkg/image/*.go`).

Because the image definitions are shared between all distributions, if I wanted to change the Fedora distribution's template to have *two* substitution markers, one for a "variant" and one for the arch, this would kinda have to apply to every ISO image type for all distributions. So we'd have to update all the image definitions and provide variants for every ISO image across Fedor and all RHEL versions, even though the concept apparently isn't really desired for RHEL. I just couldn't find a nice way to do this.

I think the solution is probably to replace the template with a *callback* at the distro level. Each distro should implement a callback function which is called with the properties of the image being built, and uses those to construct the ISO label. That way Fedora could care about variants RHEL could continue not to care about them.

I have no real knowledge of Go, though, and it's 4:30pm on Friday, so I don't feel like trying to write this (I could knock it off in ten minutes in Python, sigh).

**Comment by supakeen** [comment]
I'll write the Go code to do this correctly :)

**Comment by AdamWill** [comment]
yeah, I guess that PR resolves it sufficiently for now (and at least provides a mechanism to do better in future for things like installer images for multiple variants).
