### ISSUE TITLE
unset `AnacondaContainerInstaller.Kickstart.Path` returns an error

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/images#763]
`AnacondaContainerInstaller.Kickstart.Path` can be unset, see:

https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/image/anaconda_container_installer.go#L106

Let's trace it:

It's passed into an iso tree pipeline:
https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/image/anaconda_container_installer.go#L120

It gets passed into kickstart options:

https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/manifest/anaconda_installer_iso_tree.go#L413

It's passed into the generator of "raw kickstarts":

https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/manifest/anaconda_installer_iso_tree.go#L506

It's passed into a method creating "FS nodes":

https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/osbuild/kickstart_stage.go#L263

But this fails due to an empty path:

https://github.com/osbuild/images/blob/14f8342f5475b7a2951ee5adf847512a72e94c43/pkg/customizations/fsnode/fsnode.go#L78

---

Thus, `AnacondaContainerInstaller.Kickstart.Path` currently must be set in all cases, otherwise we will get an error. Thus, the first linked snippet doesn't make much sense, and its behaviour should probably "inverted": If `AnacondaContainerInstaller.Kickstart.Path` is unset, set it to the default path, so the same path is correctly used in all other places.

**Comment by achilleas-k** [comment]
Excellent.  Thanks for digging.  Quick PR incoming.
